config/routes.rb
Rails.application.routes.draw do
  get 'comments/create'

  get 'comments/destroy'

  resources :memos do
  resources :comments, only: [:create, :destroy]
  end
  
  devise_for :users
  root 'memos#index'
  

end

app/models/comment.rb
class Comment < ActiveRecord::Base
  belongs_to :memo
  belongs_to :user
  validates :body, presence: true
end

app/models/memo.rb
class Memo < ActiveRecord::Base
  belongs_to :user
  has_many :comments, dependent: :destroy
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
  has_many :memos
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
  before_action :set_memo
  before_action :set_comment, only: :destroy
  
  def create
    @comment = @memo.comments.new(comment_params)
    @comment.save
  end

  def destroy
    @comment.destroy
  end
  
  private
  def set_memo
   @memo = Memo.find(params[:memo_id])
  end
  
  def set_comment
  @comment = @memo.comments.find(params[:id])
  end
  
  def comment_params
  params.require(:comment).permit(:body)
  end
end

app/controllers/memos_controller.rb
class MemosController < ApplicationController
  
  before_action :authenticate_user!, except: [:index, :show]
  before_action :set_memo, only: [:show, :edit, :update, :destroy]
  
  def index
    # @memos = Memo.all
    @memos = Memo.order(created_at: :DESC) 
    # desc -->내림차순
  end

  def new
  @memo = Memo.new
  end

  def create
  @memo = Memo.new(memo_params)
  # @memo.title = params[:memo][:title]
  # @memo.content = params[:memo][:content]
  # @memo.user_id = params[:memo][:user_id]
  @memo.save
  
  
  redirect_to @memo
  end

  def edit
    # @memo = Memo.find(params[:id])
  end

  def update
  # @memo = Memo.find(params[:id])
  # @memo.title = params[:memo][:title]
  # @memo.content = params[:memo][:content]
  # @memo.user_id = params[:memo][:user_id]
  # @memo.save
  @memo.update(memo_params)
    redirect_to @memo
  end

  def destroy
  # @memo = Memo.find(params[:id])
  @memo.destroy
   redirect_to memos_path
  end
  # rake routes참고하기
  
  private
  # 컨트롤러 안에서만 쓸수 있는 프라이빗 기능 뷰에서 불러올 수 없음.
  def set_memo
    @memo = Memo.find(params[:id])
  end
  
  def memo_params
    params.require(:memo).permit(:user_id, :title, :content)
    # 위에 세가지 빼고는 못들어옴. require(:모델명)
  end
  
  def show
    # @memo = Memo.find(params[:id])
    # form for 가아닌 url로 넘어가는 거라
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/memos_helper.rb
module MemosHelper
end

app/views/comments/_comment.html.erb
<li id="comment_<%=comment.id %>">
  <%= comment.body %>,
  <%= time_ago_in_words(comment.created_at) %> ago
  <%if @memo.user == current_user%>
  <%= link_to fa_icon("times-circle-o"), [comment.memo, comment], method: :delete, remote: true, data: { confirm: "정말 삭제하시겠어요?!!!" } %>
<%end%>
</li>

app/views/comments/_comments.html.erb
<div class="comments">
  <div class="comment_header">
    <h2>댓글</h2>
  </div>
  <div class="comments_list">
    <%= render "comments/list" %>
  </div>
  <div class='comments_form'>
    <%= render "comments/form", comment: @memo.comments.new %>
  </div>
</div>

app/views/comments/_form.html.erb
<div id="comments_form_<%=comment.memo.id%>">
    <%= simple_form_for([comment.memo, comment], remote: true ) do |f| %>
    <div class='form-inputs'>
      <%= f.input :body, label: false, placeholder: '욕설이나 비방은 삼가주세요ㅜㅜ', input_html: { rows: 5 } %>
    </div>
    <div class='form-actions'>
      <%= f.button :submit %>
    </div>
    <% end %>
</div>

app/views/comments/_list.html.erb
<ul id="comments_list_<%=@memo.id%>">
<% if @memo.comments.size > 0 %>
<%= render @memo.comments %>
<% end %>
</ul>

app/views/comments/create.js.erb
<% if @comment.errors.size == 0 %>
  $('<%=j render @comment %>').appendTo($("#comments_list_<%=@memo.id %>")).hide().fadeIn('fast');
  $("#comments_form_<%=@memo.id %> form")[0].reset();
<% else %>
  alert("저장할게 없구만요 ;;");
<% end %>

app/views/comments/destroy.js.erb
$("#comment_<%=@comment.id %>").slideUp('fast');

app/views/layouts/_header.html.erb
<header class="navbar navbar-fixed-top navbar-inverse">
<div class="container">
  <%=link_to 'Memo app', root_path, id: 'logo'%>
  <nav>
    <ul class="nav navbar-nav navbar-right">
      <li><%=link_to 'Home', root_path%></li>
      <li><%=link_to 'New Memo', new_memo_path%></li>
      <% if user_signed_in?%>
      <li><%=link_to '로그아웃', destroy_user_session_path, method: :delete %></li>
      <%else%>
        <li><%=link_to '로그인', new_user_session_path %></li>
        <li><%=link_to '회원가입', new_user_registration_path %></li>
      <%end%>
    </ul>
  </nav>
</div>
</header>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Workspace</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<%=render 'layouts/header'%>
<body>

<div class="container">
<%= yield %>
</div>

</body>
</html>

app/views/memos/_form.html.erb
<%= bootstrap_form_for @memo do |f|%>
<%=f.hidden_field :user_id, value: current_user.id%>
<%=f.text_field :title, label: "제목"%><br>
<%= f.text_area :content, :class => "tinymce", :rows => 40, :cols => 120 %>
<%=f.submit '작성'%>
<%= tinymce %>
<%end%>

app/views/memos/create.html.erb
<h1>Memos#create</h1>
<p>Find me in app/views/memos/create.html.erb</p>

app/views/memos/destroy.html.erb
<h1>Memos#destroy</h1>
<p>Find me in app/views/memos/destroy.html.erb</p>

app/views/memos/edit.html.erb
<%=render 'form'%>

app/views/memos/index.html.erb
<h1>메모 인덱스 페이지</h1>
<div class="table-responsive">
    <table class="table table-fit">
        <thead>
            <tr>
                <th>title</th>
                <th>user</th>
                <th>comments</th>
            </tr>
        </thead>
        <tbody>
            <%@memos.each do |memo| %>
            <tr>
                <td><%= link_to(memo.title, memo_path(memo.id))%></td>
                <td><%=memo.user.email%></td>
                <td>100</td>
            </tr>
            <%end%>
        </tbody>
    </table>
</div>

app/views/memos/new.html.erb
<!--<h1>Memos#new</h1>-->
<!--<p>Find me in app/views/memos/new.html.erb</p>-->

<!--form_for 모델 do |f|-->
<!--form_for란, 모델과 연동이 되는 폼태그로, 수정시 매우 용이하다!-->
<!--모델이 기존에 만들어져있는지 아닌지 부터 확인해줌. -->
<!--토큰도 필요없다.-->
<!--end-->

<!--<%= bootstrap_form_for @memo do |f|%>-->
<!--<%=f.hidden_field :user_id, value: current_user.id%>-->
<!--<%=f.text_field :title, label: "제목"%><br>-->
<!--<%= f.text_area :content, :class => "tinymce", :rows => 40, :cols => 120 %>-->
<!--<%=f.submit '작성'%>-->
<!--<%= tinymce %>-->
<!--<%end%>-->

<%=render 'form'%>

app/views/memos/show.html.erb
<h1><%=@memo.title%></h1>
<hr>
<!--hr은 선을 하나 그어 주는 것-->
<h2>by <%=@memo.user.email%></h2>

<%if @memo.user == current_user%>
<!--내가 작성한 글에만 수정 삭제 가능하게-->
<%= link_to '수정', edit_memo_path%>
<%= link_to '삭제', memo_path, method: :delete %>
<%else%>
<%end%>
<hr>

<%=@memo.content.html_safe%>
<!--css태그가 적용되서 보여지는 코드-->

<!--<div class="well">-->
<!--    댓글 작성 창-->
    <%#TODO: 댓글 창 완성하기%>
<!--</div>-->
<!--<hr>-->
<!--<div>-->
<!--    댓글 보여주는 곳-->
     <%#TODO: 댓글 창 완성하기%>
<!--</div>-->
<!--grep memos 로 확인할 것-->
<%= render "comments/comments" %>

app/views/memos/update.html.erb
<h1>Memos#update</h1>
<p>Find me in app/views/memos/update.html.erb</p>